spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:

  flyway:
    enabled: false

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect