spring:
  datasource:
    driver-class-name:  com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: avro_dev_app
    password: Aa11111111
    url: "jdbc:sqlserver://avroprod.database.windows.net:1433;encrypt=true;trustServerCertificate=false;loginTimeout=30;database=test_sandbox;schema=onesub"
    dbcp2:
      default-schema: onesub
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.SQLServerDialect
      ddl-auto: none
    show-sql: true
    database: sql_server
    generate-ddl: true
    defer-datasource-initialization: false
    properties:
      hibernate:
        default_schema: onesub
        format_sql: 'false'
  sql:
    init:
      platform: sql_server
      mode: always
      continue-on-error: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

jwt:
  secret: qwepuisdhfaksdjflsdfn12321___**
  expiration: 6000000

